# Generated by Django 2.2.2 on 2019-06-22 13:32

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20190622_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=255, populate_from=['title'], unique=True),
        ),
    ]
